Google auth v2
BeNextCo/trombenext-backend pull request #14
Opened 2020-03-15 09:11 UTC by JackJack972

2020-03-16 14:58 UTC, Alezco requested changes

2020-03-16 14:58 UTC, Alezco commented on middlewares/auth.js
> +  if (req.headers['authorization'] === undefined) throw 'authorization header is missing'
`req.headers['Authorization']` ? A tester

2020-03-16 14:58 UTC, Alezco commented on middlewares/auth.js
> +  if (req.headers['authorization'] === undefined) throw 'authorization header is missing'
On peut aussi stocker cette valeur dans une variable puisque c'est utilisé 2 fois

2020-03-17 07:46 UTC, JackJack972 commented on middlewares/auth.js
> +  if (req.headers['authorization'] === undefined) throw 'authorization header is missing'
La version req.headers['Authorization'] ne fonctionne pas.

2020-03-19 14:14 UTC, Alezco approved these changes

2020-03-23 11:37 UTC, merged